spring:

  datasource:
    url: jdbc:mysql://3.38.245.93:54434/kernel360
    driver-class-name=com: com.mysql.cj.jdbc.Driver
    username: test
    password: test

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #        show-sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace