spring:

  datasource:
    url: jdbc:mysql://52.78.220.127:52848/kernel360
    driver-class-name=com: com.mysql.cj.jdbc.Driver
    username: doitfor
    password: 1q2w3e4r!@

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #        show-sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
