spring:

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/test
#    username: sa
#    password:

  datasource:
    url: jdbc:mysql://52.78.220.127:57941/kernel360
    driver-class-name=com: com.mysql.cj.jdbc.Driver
    username: doitfor
    password: 1q2w3e4r!@

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        #        show-sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
